stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - release-fetch-version
  - release-build
  - release
  #- deploy

default:
  tags:
    - asteriosphp

variables:
  DOCKER_IMAGE: registry.gitlab.com/jfheinrich-eu/docker/laravel:latest

include:
  - template: Jobs/SAST.gitlab-ci.yml
  - local: gitlab-ci/build.yml
  - local: gitlab-ci/test.yml
  - local: gitlab-ci/semver.yml