#!/usr/bin/env php
<?php declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

use Asterios\Core\Cli\Commands\AboutCommand;
use Asterios\Core\Cli\Commands\ListCommand;
use Asterios\Core\Cli\Commands\MakeModelCommand;

$commands = [
    'make:model' => new MakeModelCommand(),
    'about' => new AboutCommand(),
    'list' => new ListCommand(),
    'help' => new ListCommand(),
    '-h' => new ListCommand(),
    '--help' => new ListCommand(),

];

$input = $argv[1] ?? 'list';
$argument = $argv[2] ?? null;

if (!isset($commands[$input]))
{
    echo "\033[1;31mUnknown command:\033[0m $input\n\n";
    $commands['list']->handle(null);
    exit(1);
}

$commands[$input]->handle($argument);