#!/usr/bin/env php
<?php

declare(strict_types=1);

require_once(__DIR__ . '/vendor/autoload.php');

use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Doctrine\ORM\Tools\Console\EntityManagerProvider\SingleManagerProvider;
use Asterios\Core\Athene\Athene;
use Asterios\Core\Config;

Config::set_config_path(__DIR__ . '/src/config');

$athene = new Athene();

$commands = [];

ConsoleRunner::run(
    new SingleManagerProvider($athene->getEntityManager()),
    $commands
);
