#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    core-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^core\.ddev\.site$`)

      service: "core-web-80"
      tls: false
      # middlewares:
      #   - "core-redirectHttps"
    core-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^core\.ddev\.site$`)

      service: "core-web-8025"
      tls: false
      # middlewares:
      #   - "core-redirectHttps"
    core-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^core\.ddev\.site$`)

      service: "core-xhgui-80"
      tls: false
      # middlewares:
      #   - "core-redirectHttps"



    core-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^core\.ddev\.site$`)

      service: "core-web-80"

      tls: true

    core-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^core\.ddev\.site$`)

      service: "core-web-8025"

      tls: true


    core-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^core\.ddev\.site$`)

      service: "core-xhgui-80"

      tls: true



  middlewares:
    core-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    core-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-core-web:80

    core-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-core-web:8025



    core-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-core-xhgui:80




tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/core.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/core.key
