
# Select what we should cache between builds
cache:
  key: build_cache
  paths:
    - vendor/
    - node_modules

# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics.
test:
  stage: test
  image: ${DOCKER_IMAGE}
  needs: ['build']
  services:
    - name: mariadb:10.11@sha256:5e07c0d90fe1421e9b0b0114a7236eb519fdd873679bdb2ecc771d3c226c1f4e
      alias: db
      variables:
        MARIADB_USER: db
        MARIADB_PASSWORD: db
        MARIADB_ROOT_PASSWORD: db
        MARIADB_DATABASE: db
  variables:
    XDEBUG_MODE: coverage
  script:
    - composer tests:ci
  artifacts:
    when: always
    reports:
      junit: phpunit-report.xml
      coverage_report:
        coverage_format: cobertura
        path: phpunit-coverage.xml
    paths:
      - coverage-report/
  coverage: '/^\s+Lines:\s+[0-9]+[.][0-9]+\%/'

code-quality:
  image: ${DOCKER_IMAGE}
  needs: ['build']
  stage: test
  script:
    - composer cs-fixer:check
    - composer phpstan
  cache:
    key: build_cache
    paths:
      - vendor/
      - node_modules/
